crab submit -c Crab_MSSM_mc_WW.py
crab submit -c Crab_MSSM_mc_WZ.py
crab submit -c Crab_MSSM_mc_WZQ.py
crab submit -c Crab_MSSM_mc_ZZ.py
crab submit -c Crab_MSSM_mc_ZZQ.py
crab submit -c Crab_MSSM_mc_tWtop.py
crab submit -c Crab_MSSM_mc_tWantitop.py
crab submit -c Crab_MSSM_mc_DYJetsToLL_M50.py 
crab submit -c Crab_MSSM_mc_DYJetsToLL_M50_madgraph.py
crab submit -c Crab_MSSM_mc_TTbarJets.py
crab submit -c Crab_MSSM_mc_TTbarJets_madrgaph.py 
